import { DM_Sans } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "../../utils/SessionProvider";
import Providers from "./Providers";
import MainLayout from "./components/static/mainLayout/mainLayout";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust weights you need
  variable: "--font-dm-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased`}>
        <MainLayout>{children}</MainLayout>
        
      </body>
    </html>
  );
}
